---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
        - name: app
          image: harbor.pks.pvtl.eu/pporte/hello-world-nodejs
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
