---
apiVersion: v1
kind: Service
metadata:
  # Service name is used by IngressRoute.
  name: app
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
  selector:
    role: app